function saveFig(fig, filename, varargin)
%cleanfigure('handle', fig)
matlab2tikz(filename,                ...
            'figurehandle', fig,     ...
            'showInfo', false,       ...
            'parseStrings', false,   ...
            'width', '\figw',        ...
            'height', '\figh',       ...
            varargin{:})
end

% 'extraTikzpictureOptions','trim axis left', ...